src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom_categorie;

    /**
     * @ORM\OneToMany(targetEntity=Produit::class, mappedBy="id_categorie", orphanRemoval=true)
     */
    private $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nom_categorie;
    }
    public function __toString()
    {
        return (string) $this->getNomCategorie();
    }

    public function setNomCategorie(string $nom_categorie): self
    {
        $this->nom_categorie = $nom_categorie;

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

   

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setIdCategorie($this);
        }
  
        return $this;
    }
 
    

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->contains($produit)) {
            $this->produits->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getIdCategorie() === $this) {
                $produit->setIdCategorie(null);
            }
        }

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom_produit;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $compagnie;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix_produit;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $discription;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_categorie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nom_produit;
    }

    public function setNomProduit(string $nom_produit): self
    {
        $this->nom_produit = $nom_produit;

        return $this;
    }

    public function getcompagnie(): ?string
    {
        return $this->compagnie;
    }

    public function setcompagnie(string $compagnie): self
    {
        $this->compagnie = $compagnie;

        return $this;
    }

    public function getPrixProduit(): ?int
    {
        return $this->prix_produit;
    }

    public function setPrixProduit(int $prix_produit): self
    {
        $this->prix_produit = $prix_produit;

        return $this;
    }

    public function getdiscription(): ?string
    {
        return $this->discription;
    }

    public function setdiscription(string $discription): self
    {
        $this->discription = $discription;

        return $this;
    }

    public function getIdCategorie(): ?Categorie
    {
        return $this->id_categorie;
    }
    public function __toString()
{
    return (string) $this->getNomCategorie();
}

    public function setIdCategorie(?Categorie $id_categorie): self
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }

    
}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_categorie')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/categorie")
 */
class CategorieController extends AbstractController
{
    /**
     * @Route("/", name="categorie_index", methods={"GET"})
     */
    public function index(CategorieRepository $categorieRepository): Response
    {
        return $this->render('categorie/index.html.twig', [
            'categories' => $categorieRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="categorie_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($categorie);
            $entityManager->flush();

            return $this->redirectToRoute('categorie_index');
        }

        return $this->render('categorie/new.html.twig', [
            'categorie' => $categorie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="categorie_show", methods={"GET"})
     */
    public function show(Categorie $categorie): Response
    {
        return $this->render('categorie/show.html.twig', [
            'categorie' => $categorie,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="categorie_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Categorie $categorie): Response
    {
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('categorie_index');
        }

        return $this->render('categorie/edit.html.twig', [
            'categorie' => $categorie,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="categorie_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Categorie $categorie): Response
    {
        if ($this->isCsrfTokenValid('delete'.$categorie->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($categorie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('categorie_index');
    }
}

templates/categorie/_delete_form.html.twig
<form method="post" action="{{ path('categorie_delete', {'id': categorie.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ categorie.id) }}">
    <button class="btn">Delete</button>
</form>

templates/categorie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/categorie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Categorie{% endblock %}

{% block body %}
    <h1>Edit Categorie</h1>

    {{ include('categorie/_form.html.twig', {'button_label': 'Update'}) }}

    <a  class="btn btn-primary btn-lg active" role="button" aria-pressed="true"  href="{{ path('categorie_index') }}">back to list</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}

templates/categorie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categorie {% endblock %}

{% block body %}
<div class="jumbotron">
  <h1 class="display-3">Categorie </h1>
  <p class="lead">MIKA  informatique est la première boutique à vendre du matériel informatique en Tunisie. Depuis 2020, notre site marchand propose à ses clients toutes sortes d'articles pour usage informatique : Pc portables, Pc de bureau, tablettes, Smartphones ainsi que toutes sortes d'accessoires comme les claviers, les souris, les casques, les câbles...</p>
  <hr class="my-4">
  <form action="/searchCat" method="post" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" name="search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  <p>Tu dois ajoute nouvelle catégorie  </p>
 <p class="lead">
    <a class="btn btn-primary btn-lg"href="{{ path('categorie_new') }}" role="button">Create new Categorie</a>
  </p>
</div>
   

    <table class="table">
        <thead>
            <tr class="table-secondary">
                <th>Id</th>
                <th>Nom_categorie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for categorie in categories %}
            <tr>
                <td>{{ categorie.id }}</td>
                <td>{{ categorie.nomCategorie }}</td>
                <td>
                    <a href="{{ path('categorie_show', {'id': categorie.id}) }}"class="btn btn-primary active" role="button" aria-pressed="true">show</a>
                    <a href="{{ path('categorie_edit', {'id': categorie.id}) }}" class="btn btn-secondary active" role="button" aria-pressed="true">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
 
  
{% endblock %}

templates/categorie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Categorie{% endblock %}

{% block body %}
    <h1>Create new Categorie</h1>

    {{ include('categorie/_form.html.twig') }}

    <a class="btn btn-primary btn-lg active" role="button" aria-pressed="true" href="{{ path('categorie_index') }}">back to list</a>
{% endblock %}

templates/categorie/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categorie {% endblock %}

{% block body %}
<div class="jumbotron">
  <h1 class="display-3">Categorie </h1>
  <p class="lead">MIKA  informatique est la première boutique à vendre du matériel informatique en Tunisie. Depuis 2020, notre site marchand propose à ses clients toutes sortes d'articles pour usage informatique : Pc portables, Pc de bureau, tablettes, Smartphones ainsi que toutes sortes d'accessoires comme les claviers, les souris, les casques, les câbles...</p>
  <hr class="my-4">
  <form action="/searchCat" method="post" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" name="search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  {# <p>Tu dois ajoute nouvelle catégorie  </p> #}
 {# <p class="lead">
    <a class="btn btn-primary btn-lg"href="{{ path('categorie_new') }}" role="button">Create new Categorie</a>
  </p> #}
  Search by : {{cat}}
</div>
   

    <table class="table">
    
        <thead>
            <tr class="table-secondary">
                <th>Id</th>
                <th>nom_produit</th>
                <th>compagnie</th>
                <th>Prix_produit  </th>
                <th>Discription </th>
                <th>actions       </th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.nomProduit }}</td>
                <td>{{ produit.compagnie }}</td>
                <td>{{ produit.prixProduit }}</td>
                <td>{{ produit.discription }}</td>
                <td>
                <a href="{{ path('produit_show', {'id': produit.id}) }}" class="btn btn-primary active" role="button" aria-pressed="true">show</a>
                <a href="{{ path('produit_edit', {'id': produit.id}) }}" class="btn btn-secondary active" role="button" aria-pressed="true">edit</a>
              
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
 
  
{% endblock %}

templates/categorie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categorie{% endblock %}

{% block body %}
    <h1>Categorie</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ categorie.id }}</td>
            </tr>
            <tr>
                <th>Nom_categorie</th>
                <td>{{ categorie.nomCategorie }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary btn-lg active" role="button" aria-pressed="true" href="{{ path('categorie_index') }}">back to list</a>

    <a class="btn btn-secondary btn-lg active" role="button" aria-pressed="true"  href="{{ path('categorie_edit', {'id': categorie.id}) }}">edit</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}